### ISSUE TITLE
Testing of `pytest-ignore-flaky` fails with `pytest-enabler`

### ISSUE THREAD

**Issue by mtelka** [jaraco/pytest-enabler#11]
When I run tests for [pytest-ignore-flaky](https://github.com/schettino72/pytest-ignore-flaky) and there is `pytest-enabler` installed then the `tests/test_functional.py::test_fail_flaky` test fails there (I added `-vv` there to get more verbose output):
```
tests/test_functional.py::test_fail_flaky FAILED                         [100%]

=================================== FAILURES ===================================
_______________________________ test_fail_flaky ________________________________

testdir = <Testdir local('/tmp/pytest-of-marcel/pytest-27/test_fail_flaky0')>
capsys = <_pytest.capture.CaptureFixture object at 0x7fffadaac550>

    def test_fail_flaky(testdir, capsys):
        test = testdir.makepyfile(TEST_SAMPLE)
        rec = testdir.inline_run('-vv', test)
        results = get_results(rec)
        assert results['test_ok', 'call'] == 'passed'
>       assert results['test_mf', 'call'] == 'failed'
E       AssertionError: assert 'skipped' == 'failed'
E         - failed
E         + skipped
```
The problem seems to be this:
```
test_fail_flaky.py::test_mf XFAIL (skip flaky test failure)
```
When I modify the `test_fail_flaky` test like this:
```
--- pytest-ignore-flaky-2.0.0/tests/test_functional.py.orig
+++ pytest-ignore-flaky-2.0.0/tests/test_functional.py
@@ -34,7 +34,7 @@

 def test_fail_flaky(testdir, capsys):
     test = testdir.makepyfile(TEST_SAMPLE)
-    rec = testdir.inline_run(test)
+    rec = testdir.inline_run('-p', 'no:plugin-enabled options', test)
     results = get_results(rec)
     assert results['test_ok', 'call'] == 'passed'
     assert results['test_mf', 'call'] == 'failed'
```
then the test pass.

**Comment by jaraco** [comment]
It seems that test in pytest-ignore-flaky is specifically aiming to test that the plugin isn't run by default, but pytest-enabler aims to change that expectation. Probably if you want to test `pytest-ignore-flaky`, you should do it in isolation or disable this plugin when running those tests. I wouldn't suggest changing the pytest-ignore-flaky tests, because we don't want to entangle concerns that only affect an integrated environment.

**Comment by mtelka** [comment]
Yes, I agree.  The only problem left is that the plugin disable [does not work in some scenarios](https://github.com/jaraco/pytest-enabler/issues/10#issuecomment-1758648097).

**Comment by jaraco** [comment]
I don't think there's anything left for pytest-enabler to do here, but don't hesitate to reach out and correct my understanding.
